# Generated by Django 5.0.7 on 2025-02-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_servico_protocolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='categoria_manutencao',
        ),
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
