# Generated by Django 5.0.7 on 2025-02-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_remove_servico_categoria_manutencao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaManutencao',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
